name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar o repositório
      - name: Checkout código
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instalar dependências
      - name: Instalar dependências
        run: npm install

      # 4. Instalar navegador Chromium
      - name: Instalar Chromium
        run: npx playwright install --with-deps chromium


      # 5. Executar testes Playwright com geração de relatório HTML
      - name: Executar testes
        run: npx playwright test --reporter=html

      # 6. Salvar relatório HTML do Playwright como artefato
      - name: Salvar relatório Playwright como artefato
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      # 8. Salvar relatório HTML do Playwright como artefato
      - name: Salvar relatório Playwright como artefato
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
